### ISSUE TITLE
[Windows 11] Stuck on loading page

### ISSUE THREAD

**Issue by joatu** [lightningrodlabs/acorn#156]
On my Windows 11 laptop, when installing, the loading page never ends. Please tell me how I can share more relevant info to help identify what this bug might be. I have tried reinstalling a few times and restarting as well.

In contrast, on my Windows 10 PC, it ran perfectly without a hitch.

**Comment by Connoropolous** [comment]
hm, you may have a lingering background process somehow. This is something we have occasionally seen. 

If one holochain process was not correctly shutdown, the new one cannot start correctly. 

If you open up the thing for Windows that let's you check running processes, Task Manager I think, then search for 'holochain'. Do that while the application Acorn is quit/closed/not running. 
If you find a running 'holochain' process force quit or otherwise shut down the process. 

You may also be able to restart the computer. 

I could be wrong about this, the build runs on Windows 10 and I think that's also where we've actively tested it so far as well. 
Thanks for reporting!

**Comment by joatu** [comment]
Restarted, clicked on desktop link, same issue. Task manager, forced quit. 

Uninstalled, reinstalled and it ran automatically from the installer.

Closed it.

Clicked on desktop link. It worked. 

Closed it.

Clicked on desktop link. Same issue.

Task manager, forced quit. No lingering apps starting with the name holochain.

Clicked on desktop link. Same issue.

Task manager, forced quit.

Ran from installer (without uninstall) and it worked.

**Comment by Connoropolous** [comment]
Ok so, if I read you correctly, it sometimes works, without a clear reason why or why not. 
Very interesting. Are you willing to go further to provide us with additional details so that we can investigate the issue?

**Comment by joatu** [comment]
Happy to help. I sent you an email.
