### ISSUE TITLE
Multiple parents for an Outcome card on Map View

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#202]
Before when I had cards had more than one parent card and the tree went all over the place it was fairly compact but now it is much more spread out.

![image](https://user-images.githubusercontent.com/65631811/199334801-7c3a914c-6181-4464-8d23-386b41778438.png)

**Comment by Connoropolous** [comment]
"Before when I had cards had more than one parent card"

Technically, we haven't yet moved to officially support multiple parents per card. it typically deletes one parent when you add a different one. 

How necessary for you do you see multiple parents? Have you considered changing the 'two parents' into a Tag? That way you can associate both Outcomes with that one thing.

**Comment by Connoropolous** [comment]
Also, how did you actually manage to get an Outcome with multiple parents, lol?

**Comment by TechSupport26** [comment]
I thought I had mentioned it in a different issue but I can't find it so I will upload a video later. It was for demonstration perposes.
I have no need for multiple parent cards at the moment but I know others do.

**Comment by TechSupport26** [comment]
@Connoropolous In issue #127 I give examples of this and how I achieved it. I am testing to see if this is still possible in v2.1.1-alpha

**Comment by mitra42** [comment]
I don't think this is an edge case - In Asana, my current go-to project manager, we have many cases where a Asana.task (equivalent of an Acorn.Outcome) has multiple dependencies, for example a number of things that can't start till the budget is approved.

**Comment by jakobwinter** [comment]
I was looking for this feature just now, when planning a party:

I would like the step: **Plan menu** to be a pre-requisite for **buy food** and **buy drinks**.

**Comment by Connoropolous** [comment]
It is good to have a proposal for how to make a multi-parent connection. I see a greater challenge in how to render them. 

I have the following in mind... 
- among multiple parents, one and only one should be the designated primary. The child Outcome with multiple parents would appear rendered normally in the position as if it were only the child of that primary parent. A line connection between the child and its further afield parent would then also be drawn, but would have to be followed to its destination if that were far, to view it.

Thoughts?

**Comment by TechSupport26** [comment]
> I see a greater challenge in how to render them.

I agree, it will be quite challenging on how to render them as, when the project grows and you have more parent and child outcomes attached to multiple different sections the lines will start to intersect to connect to each other.

How important is it for the connector lines to not intersect/overlap, to have it as infrequent as possible or to have the least amount of connector lines?

![Acorn multiple parent connections sketch](https://user-images.githubusercontent.com/65631811/211666129-7bc04aea-ccec-4c8d-8ca7-baf2a22fd639.png)

**Comment by mitra42** [comment]
I don't think HOW the lines connect is so important, bendy lines, cross-overs etc are all fine, most important is to allow the dual parenting.

**Comment by maackle** [comment]
I am also wanting multiple parents. I'm glad to see discussion about it already.

I agree that it's just fundamental to the grammar of state-of-affairs, as has been pointed out. Sometimes one thing is blocking many other things, and that ought to be expressible. There are implications for sure. A lot of this thread is pointing out the significant display challenges. There also may be a decision to make on how to "count" the Smalls which are shared -- do they get split up, so if a Small has two different ancestors, perhaps it counts as 0.5 for each? (So that it adds up to 1 at the shared root.)


> I don't think HOW the lines connect is so important, bendy lines, cross-overs etc are all fine, most important is to allow the dual parenting.

I agree. Hierarchy is maintained, so even if things get a little messy, the y-coordinate gives a useful cue about dependency, and if arrows were made bold when hovering over a card, that would help trace the path. 

> requires holding down shift/control when to make the multi-parent link rather than being a "move child" operation.

I like this, I think that's how it should work.

> among multiple parents, one and only one should be the designated primary.

I can see how having a "primary" parent is useful for orienting things in 2D space, but I wouldn't expect that to extend to the fundamental grammar. I think any parent is as important as any other parent, in essence.

I'm not sure if it has discussion or its own issue, but I'd like to point out that if Outcomes could be visually rearranged by the user, that could alleviate any display problems. I do appreciate that it is nice to not have to worry about placement though...

Here's a suggestion which preserves auto-placement but gives the user some agency: Considering the idea of each outcome having a "primary parent", that implies that *any* parent could be considered the primary, which implies a different potential layout for each parent. What if the user could drag the outcome, not to arbitrarily place it, but to "snap" it into one of those alternate layouts? i.e. when the user intends to move a card, you calculate all possible layouts, and when the card moves into the proximity of where it would be in one of those alternate layouts, you see what that layout would look like. Then you don't have the trickyness of having hand-placed cards which can get wiped out next time the layout is updated, since it's just an update to the "primary parent".

This could also be a nice way to rearrange the order of cards. In general, any time a card *could* show up in another place in the layout, the user should be able to drag it to that place and see the layout change. As the layout algorithm gets more sophisticated, there would be more possible places to move cards to.
