### ISSUE TITLE
Update to access projects block can be overridden.

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#282]
This is a bit of an unintended UI/BUG.
In v-4.0.0 You can delete the project-access-blocked layer in the inspect elements.
![image](https://user-images.githubusercontent.com/65631811/236702590-8d5e392f-e234-4af2-ac2a-43d2d4ec3fc0.png)
And access your project
![image](https://user-images.githubusercontent.com/65631811/236702734-cae8581c-5926-4b5c-a579-2a203d22330c.png)
I don't think this is intended but you can still export the project and access it. (The only things I was brave enough to do so I did not experiment.)
![image](https://user-images.githubusercontent.com/65631811/236702780-2dfab63d-981c-4902-9cb7-77ee2c198fed.png)

**Comment by Connoropolous** [comment]
I am actually happy that you can do that 👍 

we still need to find better ways to manage projects during version migrations. It is still too delicate.

**Comment by Connoropolous** [comment]
@TechSupport26 
FYI, as of v7, users will be able to go back on purpose to 'migrated' versions of Acorn and override the project status so that they can continue using it, if they preferred it to a newer version, or if some other type of issue arises during migration. 

![signal-2023-08-09-123410_002](https://github.com/lightningrodlabs/acorn/assets/1409121/f331bb42-865d-4e6a-aa59-283038b7d086)

**Comment by Connoropolous** [comment]
@zippy FYI ^ 
@MvF-Evangelista this is just for your information. See the screenshot.
